name: Design Task
description: Vetted and approved work items for the design team.
labels: []
type: task
projects: ["SEMOSS/39"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search across all relevant repositories to see if an issue already exists.
    options:
    - label: I confirm that I have not found an existing or similar issue.
      required: true
- type: textarea
  attributes:
    label: Problem (why)
    description: Discuss the purpose of the design requirement so that we know why we are doing this.
  validations:
    required: true
- type: textarea
  attributes:
    label: Impact (who)
    description: Provide the key stakeholders so we know WHO we're building it for.
  validations:
    required: true
- type: textarea
  attributes:
    label: Existing
    description: Are there any relevant feature or code that should be taken into consideration?
  validations:
    required: false
- type: textarea
  attributes:
    label: Requirements (what)
    description: What are more specific requirements that needs to take to consider this issue resolved?
    placeholder: |
      - [ ] Requirement 1
      - [ ] Requirement 2
      - [ ] Requirement 3
  validations:
    required: false
