name: Epic
description: Vetted and approved idea for the project. Typically used to group multiple tasks.
title: ""
labels: []
type: epic
projects: ["SEMOSS/39"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search across all relevant repositories to see if an issue already exists.
    options:
    - label: I confirm that I have not found an existing or similar issue.
      required: true
- type: textarea
  attributes:
    label: Problem
    description: A clear and concise description of what the problem is.
    placeholder: Ex. I'm always frustrated when ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Solution
    description: A clear and concise description of what you want to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Alternatives
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context or screenshots to include.
  validations:
    required: false
- type: textarea
  attributes:
    label: Requirements or Tasks
    description: What are more specific requirements or tasks that needs to take to consider this issue resolved?
    placeholder: |
      - [ ] Task 1
      - [ ] Task 2
      - [ ] Task 3
  validations:
    required: false