name: Test Ticket
description: Vetted and approved work items.
labels: []
type: task
projects: ["SEMOSS/39"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search across all relevant repositories to see if an issue already exists.
    options:
    - label: I confirm that I have not found an existing or similar issue.
      required: true
- type: textarea
  attributes:
    label: Description
    description: Expand on the original issue to talk through what the purpose of the ticket is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Relevant Feature or Code
    description: Is there any relevant feature or code that the developer should know about when resolving this issue?
  validations:
    required: false
- type: textarea
  attributes:
    label: Requirements (what)
    description: What are more specific requirements that needs to take to consider this issue resolved?
    placeholder: |
      - [ ] Requirement 1
      - [ ] Requirement 2
      - [ ] Requirement 3
  validations:
    required: false
